name: Unity Tests
on: [workflow_dispatch, pull_request]

# Workflow based on example from https://game.ci/docs/github/test-runner/#complete-example

jobs:
  test:
    name: Run Unity Unit Tests
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            projectPath:
                - .
            testMode:
                - editmode
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Cache Unity packages
      uses: actions/cache@v3
      with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-

    - name: Run Unity tests
      uses: game-ci/unity-test-runner@v4
      env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        projectPath: ${{ matrix.projectPath }}
        testMode: ${{ matrix.testMode }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        checkName: ${{ matrix.testMode }} Test Results
        customParameters: -testFilter=Assets/Code/Tests
        unityVersion: 6000.0.47f1