name: Unity Tests
on: workflow_dispatch

jobs:
  test:
    name: Run Unity Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    - name: Cache Unity packages
      uses: actions/cache@v3
      with:
        path: ~/.unity3d
        key: ${{ runner.os }}-unity

    - name: Run Unity tests
      uses: game-ci/unity-test-runner@v4
      with:
        projectPath: .
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        unityVersion: 6000.0.47f1